# Generated by Django 4.1.3 on 2022-12-10 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagesubscriptions',
            name='Expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 9, 21, 53, 52, 522476), verbose_name='Expirty Date'),
        ),
    ]
