# Generated by Django 4.1.3 on 2022-12-10 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_alter_packagesubscriptions_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagesubscriptions',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1, verbose_name='Month'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packagesubscriptions',
            name='Expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 9, 22, 11, 29, 193876), verbose_name='Expirty Date'),
        ),
    ]
