# Generated by Django 4.1.3 on 2022-12-10 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_packagesubscriptions_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagesubscriptions',
            name='year',
            field=models.IntegerField(choices=[], default=2022, verbose_name='Year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packagesubscriptions',
            name='Expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 9, 22, 22, 16, 337359), verbose_name='Expirty Date'),
        ),
    ]
