# Generated by Django 4.1.3 on 2022-12-10 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0006_rename_connection_packagesubscriptions_connection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagesubscriptions',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 9, 23, 14, 14, 231790), verbose_name='Expirty Date'),
        ),
    ]
