# Generated by Django 4.1.3 on 2022-12-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0008_alter_packagesubscriptions_activation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagesubscriptions',
            name='activation_date',
            field=models.DateField(verbose_name='Activation Date'),
        ),
        migrations.AlterField(
            model_name='packagesubscriptions',
            name='expiry_date',
            field=models.DateField(verbose_name='Expirty Date'),
        ),
    ]
