# Generated by Django 4.1.3 on 2022-12-31 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_recevied_by_payment_received_by'),
        ('package', '0009_alter_packagesubscriptions_activation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagesubscriptions',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='payment.payment', verbose_name='Payment'),
        ),
    ]
