# Generated by Django 4.1.3 on 2022-12-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0010_packagesubscriptions_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagesubscriptions',
            name='temporary',
            field=models.BooleanField(default=False, verbose_name='Temporary Subscription'),
        ),
    ]
