# Generated by Django 4.1.3 on 2022-12-31 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0011_packagesubscriptions_temporary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagesubscriptions',
            name='temporary',
        ),
        migrations.AddField(
            model_name='packagesubscriptions',
            name='temp_expiry_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Temp. Expirty Date'),
            preserve_default=False,
        ),
    ]
