# Generated by Django 4.1.3 on 2022-12-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0012_remove_packagesubscriptions_temporary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagesubscriptions',
            name='temp_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Temp. Expirty Date'),
        ),
    ]
