# Generated by Django 4.1.3 on 2023-01-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0014_alter_packagesubscriptions_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagesubscriptions',
            name='month',
        ),
        migrations.RemoveField(
            model_name='packagesubscriptions',
            name='year',
        ),
    ]
