# Generated by Django 4.1.3 on 2022-11-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('contact', models.CharField(blank=True, max_length=50, verbose_name='Contact')),
                ('biography', models.TextField(blank=True, verbose_name='Biography')),
                ('steet_address', models.TextField(blank=True, verbose_name='Steet Address')),
                ('area', models.TextField(blank=True, verbose_name='Area')),
                ('city', models.TextField(blank=True, verbose_name='City')),
                ('image', models.ImageField(default='media/images/avatar.jpg', upload_to='images')),
            ],
        ),
    ]
