# Generated by Django 4.1.3 on 2022-11-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='/images/avatar.jpg', upload_to='images'),
        ),
    ]
