# Generated by Django 4.1.3 on 2022-11-15 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='steet_address',
            new_name='street_address',
        ),
    ]
