# Generated by Django 4.1.3 on 2022-12-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customer_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Dealer', 'Dealer')], default='Individual', max_length=15, verbose_name='Type'),
        ),
    ]
