# Generated by Django 4.1.3 on 2022-12-08 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Product Catagory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Product Type')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('sku', models.CharField(max_length=50, verbose_name='SKU')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('purchase_price', models.IntegerField(blank=True, null=True, verbose_name='Purchase Price')),
                ('sale_price', models.IntegerField(blank=True, null=True, verbose_name='Sale Price')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.productcatagory', verbose_name='Product Catagory')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.producttype', verbose_name='Product Type')),
            ],
        ),
    ]
