# Generated by Django 4.1.3 on 2022-12-10 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_unit_product_unit'),
    ]

    operations = [

    ]
