# Generated by Django 4.1.3 on 2022-12-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.IntegerField(default=0, verbose_name='Purchase Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(default=0, verbose_name='Sale Price'),
        ),
    ]
