# Generated by Django 4.1.3 on 2022-12-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Value'),
        ),
    ]
