# Generated by Django 4.1.3 on 2023-01-05 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_unit_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcatagory',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='catagories', to='product.producttype', verbose_name='Type'),
            preserve_default=False,
        ),
    ]
