# Generated by Django 4.1.3 on 2023-01-05 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productcatagory_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
    ]
