# Generated by Django 4.1.3 on 2023-01-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Value'),
        ),
    ]
