# Generated by Django 4.1.3 on 2022-12-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_recevied_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='recevied_by',
            new_name='received_by',
        ),
    ]
