# Generated by Django 4.1.3 on 2022-12-24 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0002_rename_county_country_alter_city_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('designation', models.CharField(max_length=20, verbose_name='Designation')),
                ('contact', models.CharField(blank=True, max_length=50, verbose_name='Contact')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('street_address', models.TextField(blank=True, verbose_name='Steet Address')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('biography', models.TextField(blank=True, verbose_name='Biography')),
                ('subarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='location.subarea', verbose_name='Sub Area')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
