# Generated by Django 4.1.3 on 2022-12-24 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='subarea',
        ),
    ]
