# Generated by Django 4.1.3 on 2023-01-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='temp_validity_extension',
            field=models.IntegerField(default=5, verbose_name='Temporary Validity Extension'),
        ),
    ]
