# Generated by Django 4.1.3 on 2023-01-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_setting_temp_validity_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='bill_auto_print',
            field=models.BooleanField(default=True, verbose_name='Bill Auto Print'),
        ),
    ]
