# Generated by Django 4.1.3 on 2022-11-25 17:56

import connection.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0004_rename_steet_address_customer_street_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.CharField(default=-1, max_length=50, verbose_name='Connection ID')),
                ('package', models.CharField(blank=True, max_length=25, null=True, verbose_name='Package')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='customer.customer', verbose_name='Customer')),
            ],
        ),
    ]
