# Generated by Django 4.1.3 on 2022-11-25 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='installation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Installation Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='connection',
            name='connection_id',
            field=models.CharField(default=-1, max_length=50, verbose_name='Connection ID'),
        ),
    ]
