# Generated by Django 4.1.3 on 2022-11-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_connection_installation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='installation_date',
            field=models.DateField(verbose_name='Installation Date'),
        ),
    ]
