# Generated by Django 4.1.3 on 2022-11-25 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0003_alter_connection_installation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='installation_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Installation Date'),
        ),
    ]
