# Generated by Django 4.1.3 on 2022-11-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0004_alter_connection_installation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20, verbose_name='Status'),
        ),
    ]
