# Generated by Django 4.1.3 on 2022-11-26 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rename_steet_address_customer_street_address'),
        ('connection', '0006_remove_connection_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='customer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='customer.customer', verbose_name='Customer'),
            preserve_default=False,
        ),
    ]
