# Generated by Django 4.1.3 on 2022-11-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0007_connection_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='customer',
        ),
    ]
