# Generated by Django 4.1.3 on 2022-11-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0009_connection_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='new',
            field=models.BooleanField(default=True, verbose_name='New Connection'),
        ),
    ]
