# Generated by Django 4.1.3 on 2022-12-08 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0011_connection_subarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Created'),
            preserve_default=False,
        ),
    ]
