# Generated by Django 4.1.3 on 2022-12-10 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_purchase_price_and_more'),
        ('connection', '0012_connection_date_created'),
    ]

    operations = [
    ]
