# Generated by Django 4.1.3 on 2022-12-10 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0015_alter_connection_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='package',
        ),
    ]
