# Generated by Django 4.1.3 on 2022-12-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0019_alter_connection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='connection',
            name='renewal',
            field=models.BooleanField(default=False, verbose_name='Renewal'),
        ),
    ]
