# Generated by Django 4.1.3 on 2022-11-25 11:24

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Theme Title')),
            ],
        ),
        migrations.CreateModel(
            name='ThemeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=20, samples=None, verbose_name='Text Color')),
                ('field_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=20, samples=None, verbose_name='Field Text Color')),
                ('border_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=20, samples=None, verbose_name='Border Color')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='theme.theme', verbose_name='Theme')),
            ],
        ),
    ]
