# Generated by Django 4.1.3 on 2022-12-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=0, max_length=50, verbose_name='Order ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Partial', 'Partial'), ('Completed', 'Completed')], default='Pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Order Value'),
        ),
    ]
