# Generated by Django 4.1.3 on 2022-12-14 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_purchase_price_and_more'),
        ('order', '0004_orderdetail_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detials', to='product.product', verbose_name='Product'),
            preserve_default=False,
        ),
    ]
