# Generated by Django 4.1.3 on 2022-12-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_orderdetail_product_orderdetail_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Balance',
            field=models.IntegerField(default=0, verbose_name='Balance'),
        ),
    ]
