# Generated by Django 4.1.3 on 2022-12-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Balance',
            new_name='balance',
        ),
    ]
