# Generated by Django 4.1.3 on 2022-12-20 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_rename_balance_order_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='order',
            name='value',
        ),
    ]
