# Generated by Django 4.1.3 on 2022-12-31 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_orderpackagedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpackagedetail',
            name='package',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='order.orderdetail', verbose_name='Package'),
        ),
    ]
