# Generated by Django 4.1.3 on 2023-01-01 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_orderpackagedetail_valid_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpackagedetail',
            name='package',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='packagedetails', to='order.orderdetail', verbose_name='Package'),
        ),
    ]
